[package]
name = "vimwikid"
version = "0.1.0"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
clap = "3.0.0-beta.1"
nom = "5.1.2"
serde = "1.0.114"
serde_json = "1.0.57"
