[package]
name = "vimwiki"
version = "0.1.0-alpha.1"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.15", features = ["serde"] }
nom = "5.1.2"
nom_locate = "2.0.0"
numerals = "0.1.4"
rstar = { version = "0.8.2", features = ["serde"] }
serde = { version = "1.0.115", features = ["derive"] }
shellexpand = "2.0.0"
uriparse = { version = "0.6.3", features = ["serde"] }

[dependencies.derive_more]
version = "0.99.0"
default-features = false
features = [
    "as_mut",
    "as_ref",
    "constructor",
    "deref",
    "deref_mut",
    "display",
    "error",
    "from",
    "index",
    "index_mut",
    "into",
    "into_iterator",
    "try_into",
]

[dependencies.petgraph]
version = "0.5.1"
default-features = false
features = ["serde-1"]

[dev-dependencies]
indoc = "1.0.2"
vimwiki_macros = { version = "0.1.0-alpha.1", path = "../vimwiki_macros" }
